### ISSUE TITLE
Emulator nightly does not work on macos mojave - 10.14.1 and ubuntu

### ISSUE THREAD

**Issue by vishwacsena** [Microsoft/BotFramework-Emulator#1153]
## Version
4.1.45039 (latest nightly)

## Describe the bug
Emulator installs but fails to launch with the following error 

Process:               Bot Framework Emulator [1760]
Path:                  /Applications/Bot Framework Emulator.app/Contents/MacOS/Bot Framework Emulator
Identifier:            F3C061A6-FE81-4548-82ED-C1171D9856BB
Version:               4.1.0 (4.1.0.45039)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           Bot Framework Emulator [1760]
User ID:               501

Date/Time:             2018-12-07 11:04:54.817 -0800
OS Version:            Mac OS X 10.14.1 (18B75)
Report Version:        12
Bridge OS Version:     3.1 (16P1065)
Anonymous UUID:        7A2675C9-CCBB-C3B0-7EB4-7087ACA9C460

Sleep/Wake UUID:       48FF2070-25B1-401B-8C27-F0C85B88E0E3

Time Awake Since Boot: 5100 seconds
Time Since Wake:       65 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: @rpath/Electron Framework.framework/Electron Framework
  Referenced from: /Applications/Bot Framework Emulator.app/Contents/MacOS/Bot Framework Emulator
  Reason: image not found

Binary Images:
       0x1076eb000 -        0x1076ebff7 +F3C061A6-FE81-4548-82ED-C1171D9856BB (4.1.0 - 4.1.0.45039) <5D51F11B-3CC9-3193-BD67-27427F5B22BA> /Applications/Bot Framework Emulator.app/Contents/MacOS/Bot Framework Emulator
       0x115956000 -        0x1159d46a7  dyld (635.2) <1780094A-8FE2-3EAA-B4A3-C4CF14BC5196> /usr/lib/dyld
    0x7fff2d49e000 -     0x7fff2d5a8ff3  com.apple.Bluetooth (6.0.9 - 6.0.9f2) <0EDECAF3-FF86-3F7D-B916-2D7E67FF67AE> /System/Library/Frameworks/IOBluetooth.framework/Versions/A/IOBluetooth

Model: MacBookPro15,1, BootROM 220.220.102.0.0 (iBridge: 16.16.1065.0.0,0), 6 processors, Intel Core i7, 2.2 GHz, 32 GB, SMC 
Graphics: Intel UHD Graphics 630, Intel UHD Graphics 630, Built-In
Graphics: Radeon Pro 555X, Radeon Pro 555X, PCIe
Memory Module: BANK 0/ChannelA-DIMM0, 16 GB, DDR4, 2400 MHz, Micron, 16ATS2G64HZ-2G6B1 16ATS2G64HZ-2G6B1
Memory Module: BANK 2/ChannelB-DIMM0, 16 GB, DDR4, 2400 MHz, Micron, 16ATS2G64HZ-2G6B1 16ATS2G64HZ-2G6B1
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x7BF), wl0: Sep 18 2018 16:24:57 version 9.130.86.7.32.6.21 FWID 01-83a3fe91
Bluetooth: Version 6.0.9f2, 3 services, 27 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
USB Device: USB 3.1 Bus
USB Device: iBridge Bus
USB Device: iBridge DFR brightness
USB Device: iBridge Display
USB Device: Apple Internal Keyboard / Trackpad
USB Device: Headset
USB Device: iBridge ALS
USB Device: iBridge FaceTime HD Camera (Built-in)
USB Device: iBridge
Thunderbolt Bus: MacBook Pro, Apple Inc., 34.6
Thunderbolt Bus: MacBook Pro, Apple Inc., 34.6

[bug]

**Comment by vishwacsena** [comment]
Also there are two mac dmg files in the nightly build. both fail to launch. We should clean up the list so there is only set of installers for mac.

**Comment by vishwacsena** [comment]
Build 4.1.44959 installs and works on my mac.

**Comment by vishwacsena** [comment]
parallels@parallels-Parallels-Virtual-Platform:~/Downloads$ chmod a+x ./BotFramework-Emulator-4.1.45039-linux-x86_64.AppImage 
parallels@parallels-Parallels-Virtual-Platform:~/Downloads$ ./BotFramework-Emulator-4.1.45039-linux-x86_64.AppImage 
{"name":"Emulator","hostname":"parallels-Parallels-Virtual-Platform","pid":3538,"level":40,"msg":"DEPRECATION WARNING: Due to deprecation of the domain module in node.js, all features in restify that depend on it have been deprecated as well. This includes `handleUncaughtExceptions` and `next.ifError()`. They will continue to work in 5.x, but consider them unsupported and likely to be removed from future versions of restify.","time":"2018-12-07T19:36:40.928Z","v":0}
{"name":"Emulator","hostname":"parallels-Parallels-Virtual-Platform","pid":3538,"level":40,"msg":"DEPRECATION WARNING: Due to deprecation of the domain module in node.js, all features in restify that depend on it have been deprecated as well. This includes `handleUncaughtExceptions` and `next.ifError()`. They will continue to work in 5.x, but consider them unsupported and likely to be removed from future versions of restify.","time":"2018-12-07T19:36:40.928Z","v":0}
Failed to read file: /home/parallels/.config/@bfemulator/main/botframework-emulator/server.json { Error: ENOENT: no such file or directory, stat '/home/parallels/.config/@bfemulator/main/botframework-emulator/server.json'
    at fs.statSync (fs.js:954:11)
    at Object.fs.statSync (ELECTRON_ASAR.js:295:16)
    at Object.statSync (/tmp/.mount_BotFraOiHY3a/resources/app.asar/node_modules/graceful-fs/polyfills.js:297:22)
    at loadSettings (/tmp/.mount_BotFraOiHY3a/resources/app.asar/app/server/utils/loadSettings.js:57:21)
    at getStore (/tmp/.mount_BotFraOiHY3a/resources/app.asar/app/server/settingsData/store.js:67:53)
    at NgrokService.cacheSettings (/tmp/.mount_BotFraOiHY3a/resources/app.asar/app/server/ngrokService.js:221:43)
    at NgrokService.startup (/tmp/.mount_BotFraOiHY3a/resources/app.asar/app/server/ngrokService.js:96:10)
    at Emulator.startup (/tmp/.mount_BotFraOiHY3a/resources/app.asar/app/server/emulator.js:74:22)
    at <anonymous>
    at process._tickDomainCallback (internal/process/next_tick.js:228:7)
  errno: -2,
  code: 'ENOENT',
  syscall: 'stat',
  path: '/home/parallels/.config/@bfemulator/main/botframework-emulator/server.json' }
The preloadedState argument passed to createStore has unexpected type of "Object". Expected argument to be an object with the following keys: "azure", "framework", "bots", "windowState", "users"
Error reading file /home/parallels/.config/@bfemulator/main/botframework-emulator/bots.json: Error: ENOENT: no such file or directory, stat '/home/parallels/.config/@bfemulator/main/botframework-emulator/bots.json'
The previous state received by the reducer has unexpected type of "Object". Expected argument to be an object with the following keys: "azure", "framework", "bots", "windowState", "users"
Adding extension JSON
Adding extension LUIS
Adding extension QNAMaker
(node:3538) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): There was an error while checking for the latest update: Error: Cannot find latest-linux.yml in the latest release artifacts (https://github.com/Microsoft/BotFramework-Emulator/releases/download/v3.5.37/latest-linux.yml): HttpError: 404 Not Found
"method: undefined url: https://github.com/Microsoft/BotFramework-Emulator/releases/download/v3.5.37/latest-linux.yml\n\nPlease double check that your authentication token is correct. Due to security reasons actual status maybe not reported, but 404.\n"
Headers: {
  "cache-control": [
    "no-cache"
  ],
  "content-encoding": [
    "gzip"
  ],
  "content-security-policy": [
    "default-src 'none'; base-uri 'self'; connect-src 'self'; form-action 'self'; img-src 'self' data:; script-src 'self'; style-src 'unsafe-inline'"
  ],
  "content-type": [
    "text/plain; charset=utf-8"
  ],
  "date": [
    "Fri, 07 Dec 2018 19:40:04 GMT"
  ],
  "expect-ct": [
    "max-age=2592000, report-uri=\"https://api.github.com/_private/browser/errors\""
  ],
  "server": [
    "GitHub.com"
  ],
  "set-cookie": [
    "has_recent_activity=1; path=/; expires=Fri, 07 Dec 2018 20:40:04 -0000",
    "logged_in=no; domain=.github.com; path=/; expires=Tue, 07 Dec 2038 19:40:04 -0000; secure; HttpOnly",
    "_gh_sess=VXFLd0VBMHNOaEsrbDdQd0hOTEZ5TUYvS1gyd3BrSFYrZ1Fvb2hnQ0NyN3FvZ1UrMWxjdmVFdWZQMVA2SnVMUTVCRlo3M2lCTFZ1MVJwMSs3RXV6S0l1ZGZKaGFMMEVtZXNsQjVZOXJSNHE3QVBOdXFyZHM3S0xLa2h4ZEZBMzZKMTJuSGI0SFZBRFM0K0E1dk9od1FGemZ1Q0RZb3R6OTV1UHN0dXRBQTl4TGtGZ3I1WHJUdEVuSHNJMTFpT0xYMFJtVFBHZjM2OE1TTkNlRnBCWldZQT09LS03OFhHUk5IOXNEanV2ZmdDRzZPam13PT0%3D--7be177e97bf6e0c878eb632b7cf5fc4ef304f048; path=/; secure; HttpOnly"
  ],
  "status": [
    "404 Not Found"
  ],
  "strict-transport-security": [
    "max-age=31536000; includeSubdomains; preload"
  ],
  "transfer-encoding": [
    "chunked"
  ],
  "vary": [
    "X-PJAX"
  ],
  "x-content-type-options": [
    "nosniff"
  ],
  "x-frame-options": [
    "deny"
  ],
  "x-github-request-id": [
    "A3D2:0943:D8174:148987:5C0ACC94"
  ],
  "x-request-id": [
    "64590072-fab2-4e7e-bdf8-17fbf438d021"
  ],
  "x-xss-protection": [
    "1; mode=block"
  ]
}
    at createHttpError (/tmp/.mount_BotFraOiHY3a/resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:32:10)
    at ElectronHttpExecutor.handleResponse (/tmp/.mount_BotFraOiHY3a/resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:130:14)
    at ClientRequest.request.doRequest.response (/tmp/.mount_BotFraOiHY3a/resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:87:16)
    at emitOne (events.js:116:13)
    at ClientRequest.emit (events.js:211:7)
    at URLRequest.ClientRequest.urlRequest.on (/tmp/.mount_BotFraOiHY3a/resources/electron.asar/browser/api/net.js:207:12)
    at emitOne (events.js:116:13)
    at URLRequest.emit (events.js:211:7)
From previous event:
    at CancellationToken.createPromise (/tmp/.mount_BotFraOiHY3a/resources/app.asar/node_modules/builder-util-runtime/src/CancellationToken.ts:51:12)
    at ElectronHttpExecutor.doApiRequest (/tmp/.mount_BotFraOiHY3a/resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:84:30)
    at ElectronHttpExecutor.request (/tmp/.mount_BotFraOiHY3a/resources/app.asar/node_modules/builder-util-runtime/src/httpExecutor.ts:74:17)
    at /tmp/.mount_BotFraOiHY3a/resources/app.asar/node_modules/electron-updater/src/providers/GitHubProvider.ts:74:38
From previous event:
    at GitHubProvider.getLatestVersion (/tmp/.mount_BotFraOiHY3a/resources/app.asar/node_modules/electron-updater/src/providers/GitHubProvider.ts:35:25)
    at /tmp/.mount_BotFraOiHY3a/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:345:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at AppImageUpdater.getUpdateInfo (/tmp/.mount_BotFraOiHY3a/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:335:32)
    at /tmp/.mount_BotFraOiHY3a/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:349:35
    at Generator.next (<anonymous>)
From previous event:
    at AppImageUpdater.doCheckForUpdates (/tmp/.mount_BotFraOiHY3a/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:348:34)
    at /tmp/.mount_BotFraOiHY3a/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:287:25
    at Generator.next (<anonymous>)
    at runCallback (timers.js:789:20)
    at tryOnImmediate (timers.js:751:5)
    at processImmediate [as _immediateCallback] (timers.js:722:5)
From previous event:
    at AppImageUpdater._checkForUpdates (/tmp/.mount_BotFraOiHY3a/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:282:33)
    at AppImageUpdater.checkForUpdates (/tmp/.mount_BotFraOiHY3a/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:221:35)
    at Object.checkForUpdates (/tmp/.mount_BotFraOiHY3a/resources/app.asar/src/appUpdater.ts:161:29)
    at Object.checkForUpdates [as startup] (/tmp/.mount_BotFraOiHY3a/resources/app.asar/src/appUpdater.ts:144:12)
    at BrowserWindow.startup (/tmp/.mount_BotFraOiHY3a/resources/app.asar/src/main.ts:393:16)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at BrowserWindow.emit (events.js:211:7)
(node:3538) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by tonyanziano** [comment]
- Broken mac build appears to be transient, I [published a new nightly build](https://github.com/Microsoft/botframework-emulator-nightlies/releases/tag/v4.1.45083) and it seems to be working
- Fixed the duplicate mac artifact issue
- Was unable to repro the hanging launch issue on Ubuntu 64-bit 18.0.4. Even deleting the `server.json` and relaunching the app was unable to repro
