### ISSUE TITLE
Bot emulator sent message results in BadRequest when hosted with gitpod

### ISSUE THREAD

**Issue by rinormaloku** [Microsoft/BotFramework-Emulator#1158]
## Version
4.1.5

## Describe the bug
The Bot Application works locally but returns Bad Request and throws the following exception when hosted (using gitpod) and connecting to it with **Bot Framework Emulator**:

```
info: Microsoft.AspNetCore.Server.Kestrel[17]
      Connection id "0HLIT29JMM76O" bad request data: "Requests with 'Connection: Upgrade' cannot have content in the request body."
Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException: Requests with 'Connection: Upgrade' cannot have content in the request body.
   at Microsoft.AspNetCore.Server.Kestrel.Core.BadHttpRequestException.Throw(RequestRejectionReason reason)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Http1MessageBody.For(HttpVersion httpVersion, HttpRequestHeaders headers, Http1Connection context)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequestsAsync[TContext](IHttpApplication`1 application)
```

## To Reproduce
1. Open [the project](https://github.com/rinormaloku/bot-gitpod) with Gitpod: https://gitpod.io/#https://github.com/rinormaloku/bot-gitpod
2. Run the app: `dotnet run --project EchoBot/EchoBot/EchoBot.csproj` 
3. Open Bot Framework Emulator (4.1.x) and Connect to the endpoint provided by gitpod.
4. Use ngrok for tunnelling.
5. Write anything to the bot.

## Expected behavior
No exception should be thrown.

[bug]

**Comment by justinwilaby** [comment]
Looks like GitPod may be using an incompatible http protocol as indicated by `Connection: Upgrade` in the header.

**Comment by justinwilaby** [comment]
Looks like this is related to a [Krestel defect](https://github.com/aspnet/KestrelHttpServer/issues/2372). I do not believe this is a defect in the Emulator.
