### ISSUE TITLE
Error processing argument at index 2, conversion failure from #<Object>

### ISSUE THREAD

**Issue by ckartchner** [Microsoft/BotFramework-Emulator#1182]
## Version
I am running that latest appimage under Linux mint
BotFramework-Emulator-4.2.0-linux-x86_64.AppImage

I also reproduced the issue with: 
BotFramework-Emulator-4.1.0-linux-x86_64.AppImage

## Describe the bug
When I start the Bot Framework Emulator, I see the following message:
`Error occurred while client was loading: Error processing argument at index 2, conversion failure from #<Object>`

When I try to add a bot, I see a very similar error:
`Error while setting active bot: Error processing argument at index 2, conversion failure from #<Object>`

It may also be relevant that, after adding the bot, I can't communicate with it until after a change is made in the settings. It doesn't matter what is changed there only that I change something. (Checking auth boxes, changing localhost override... they all do the trick). This issue appeared at the same time as the argument processing error so I believe they have the same root cause.

## To Reproduce
Open AppImage
Check notifications

I cannot reproduce this issue on other systems. It appears something is broken in my local environment.

## Expected behavior
No error
No need to go to settings and make an arbitrary change before bot can be accessed.

## Additional context
When I run 4.1.0 from the CLI is get the following more detailed output:
`TypeError: Error processing argument at index 2, conversion failure from #<Object>
    at Object.normal (/tmp/.mount_BotFrabt0Yn0/app/resources/electron.asar/browser/api/menu.js:260:24)
    at Menu.insertItemByType (/tmp/.mount_BotFrabt0Yn0/app/resources/electron.asar/browser/api/menu.js:287:19)
    at Menu.insert (/tmp/.mount_BotFrabt0Yn0/app/resources/electron.asar/browser/api/menu.js:111:20)
    at Menu.append (/tmp/.mount_BotFrabt0Yn0/app/resources/electron.asar/browser/api/menu.js:102:15)
    at positioned.forEach (/tmp/.mount_BotFrabt0Yn0/app/resources/electron.asar/browser/api/menu.js:178:10)
    at Array.forEach (<anonymous>)
    at Function.Menu.buildFromTemplate (/tmp/.mount_BotFrabt0Yn0/app/resources/electron.asar/browser/api/menu.js:174:14)
    at new MenuItem (/tmp/.mount_BotFrabt0Yn0/app/resources/electron.asar/browser/api/menu-item.js:19:25)
    at positioned.forEach (/tmp/.mount_BotFrabt0Yn0/app/resources/electron.asar/browser/api/menu.js:178:17)
    at Array.forEach (<anonymous>)
    at Function.Menu.buildFromTemplate (/tmp/.mount_BotFrabt0Yn0/app/resources/electron.asar/browser/api/menu.js:174:14)
    at new MenuItem (/tmp/.mount_BotFrabt0Yn0/app/resources/electron.asar/browser/api/menu-item.js:19:25)
    at positioned.forEach (/tmp/.mount_BotFrabt0Yn0/app/resources/electron.asar/browser/api/menu.js:178:17)
    at Array.forEach (<anonymous>)
    at Function.Menu.buildFromTemplate (/tmp/.mount_BotFrabt0Yn0/app/resources/electron.asar/browser/api/menu.js:174:14)
    at AppMenuBuilderImpl.buildFromTemplate [as refreshAppUpdateMenu] (/tmp/.mount_BotFrabt0Yn0/app/resources/app.asar/src/appMenuBuilder.ts:435:52)
From previous event:
    at AppImageUpdater._checkForUpdates (/tmp/.mount_BotFrabt0Yn0/app/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:282:33)
    at AppImageUpdater.checkForUpdates (/tmp/.mount_BotFrabt0Yn0/app/resources/app.asar/node_modules/electron-updater/src/AppUpdater.ts:221:35)
    at Object.checkForUpdates (/tmp/.mount_BotFrabt0Yn0/app/resources/app.asar/src/appUpdater.ts:137:25)
    at BrowserWindow.checkForUpdates (/tmp/.mount_BotFrabt0Yn0/app/resources/app.asar/src/main.ts:363:18)
    at Object.onceWrapper (events.js:315:30)
    at emitOne (events.js:116:13)
    at BrowserWindow.emit (events.js:211:7)
`

**Comment by ckartchner** [comment]
I was able to recover by deleting the electron app config settings.

Remove the following:
~/.config/@bfemulator/ 

If I figure out how to repro the problem I'll open a separate issue, but things are running smoothly for me again so I'm happy. 

I also ran `git diff --no-index @bfemulator @bfemulator_original`, and didn't see any obviously bad differences with the non-binary files.
