### ISSUE TITLE
Uncaught exception: Could not call remote function

### ISSUE THREAD

**Issue by LarsLiden** [Microsoft/BotFramework-Emulator#147]
[12:10:22] [err-client] Uncaught Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: Error processing argument at index 0, conversion failure from null Error: Could not call remote function ''. Check that the function signature is correct. Underlying error: Error processing argument at index 0, conversion failure from null at callFunction (C:\Users\laliden\AppData\Local\botframework\app-3.5.25\resources\electron.asar\browser\rpc-server.js:228:11) at EventEmitter.<anonymous> (C:\Users\laliden\AppData\Local\botframework\app-3.5.25\resources\electron.asar\browser\rpc-server.js:316:5) at emitMany (events.js:127:13) at EventEmitter.emit (events.js:201:7) at WebContents.<anonymous> (C:\Users\laliden\AppData\Local\botframework\app-3.5.25\resources\electron.asar\browser\api\web-contents.js:219:13) at emitTwo (events.js:106:13) at WebContents.emit (events.js:191:7) C:\Users\laliden\AppData\Local\botframework\app-3.5.25\resources\electron.asar\renderer\api\remote.js 217 7 {}

**Comment by eanders-MS** [comment]
Thanks @LarsLiden. What were you doing when you got this error? Was it at startup?

**Comment by LarsLiden** [comment]
No, I'd been using the emulator for a while.

**Comment by eanders-MS** [comment]
Closing this issue due to lack of actionable info and no repro.
