### ISSUE TITLE
I am recently having following issu with my emulator. Version ngrok 2.2.4

### ISSUE THREAD

**Issue by m-ehxan** [Microsoft/BotFramework-Emulator#156]
Command failed: 4294967295 System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The remote server returned an error: (500) Internal Server Error.
 at System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
 at System.Net.WebClient.GetWebResponse(WebRequest request, IAsyncResult result)
 at System.Net.WebClient.DownloadBitsResponseCallback(IAsyncResult result)
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Squirrel.Utility.<LogIfThrows>d__35`1.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Squirrel.FileDownloader.<DownloadUrl>d__3.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
 at Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Squirrel.UpdateManager.<CheckForUpdate>d__7.MoveNext()
 --- End of stack trace from previous location where exception was thrown ---
 at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
 at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
 at Squirrel.Update.Program.<Download>d__7.MoveNext()
 --- End of inner exception stack trace ---
 at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
 at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
 at System.Threading.Tasks.Task`1.get_Result()
 at Squirrel.Update.Program.executeCommandLine(String[] args)
 at Squirrel.Update.Program.main(String[] args)
 at Squirrel.Update.Program.Main(String[] args)
 ---> (Inner Exception #0) System.Net.WebException: The remote server

**Comment by m-ehxan** [comment]
![capture](https://cloud.githubusercontent.com/assets/13121723/24852209/fbe8fb10-1dd6-11e7-88e8-2727989802cf.PNG)

**Comment by eanders-MS** [comment]
Hi @m-ehxan, Thanks for taking the time to report this. The source of this error is our auto-updater on Windows, which has reliability issues. The emulator itself is functioning fine. We are aware of this problem, and are planning a redesign of our auto-update system for better stability and reliability.

**Comment by eanders-MS** [comment]
Next version of the emulator will ignore this error (because its harmless).
