### ISSUE TITLE
Error: Module version mismatch. Expected 50, got 51 when running locally

### ISSUE THREAD

**Issue by peterblazejewicz** [Microsoft/BotFramework-Emulator#21]
I've always got that error when running emulator locally under Node v7.0.* and v.6.6.*:
```
npm run start

> botframework-emulator@3.5.20 start /Users/piotrblazejewicz/git/BotFramework-Emulator
> electron .

Error: Module version mismatch. Expected 50, got 51.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:178:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:178:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/piotrblazejewicz/git/BotFramework-Emulator/node_modules/bunyan/node_modules/dtrace-provider/dtrace-provider.js:17:23)
{ Error: Cannot find module './build/default/DTraceProviderBindings'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/Users/piotrblazejewicz/git/BotFramework-Emulator/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/piotrblazejewicz/git/BotFramework-Emulator/node_modules/bunyan/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/Debug/DTraceProviderBindings'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/Users/piotrblazejewicz/git/BotFramework-Emulator/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/piotrblazejewicz/git/BotFramework-Emulator/node_modules/bunyan/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12) code: 'MODULE_NOT_FOUND' }
Error: Module version mismatch. Expected 50, got 51.
    at Error (native)
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:178:20)
    at Object.Module._extensions..node (module.js:583:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:178:20)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12)
    at Function.Module._load (module.js:424:3)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/piotrblazejewicz/git/BotFramework-Emulator/node_modules/dtrace-provider/dtrace-provider.js:17:23)
{ Error: Cannot find module './build/default/DTraceProviderBindings'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/Users/piotrblazejewicz/git/BotFramework-Emulator/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/piotrblazejewicz/git/BotFramework-Emulator/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12) code: 'MODULE_NOT_FOUND' }
{ Error: Cannot find module './build/Debug/DTraceProviderBindings'
    at Module._resolveFilename (module.js:455:15)
    at Function.Module._resolveFilename (/Users/piotrblazejewicz/git/BotFramework-Emulator/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:35:12)
    at Function.Module._load (module.js:403:25)
    at Module.require (module.js:483:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/Users/piotrblazejewicz/git/BotFramework-Emulator/node_modules/dtrace-provider/dtrace-provider.js:17:23)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
    at Module.load (module.js:473:32)
    at tryModuleLoad (module.js:432:12) code: 'MODULE_NOT_FOUND' }
restarting Emulator because undefined !== 9002
```

There is nothing obvious for me on this error log unfortunately.

**Comment by eanders-MS** [comment]
@peterblazejewicz What platform are you running?

**Comment by peterblazejewicz** [comment]
@eanders-MS sorry, this was on OS X (Sierra). On the Windows OS I'm getting a different error, on startup, not this one.

**Comment by eanders-MS** [comment]
Ok. On OS X can you post the result of running the command `npm install`. Some of the dependencies require compilation. I'm wondering if any of the steps are reporting errors.

Also would like to know the errors you're seeing on Windows.

**Comment by eanders-MS** [comment]
Hi @peterblazejewicz Are you still experiencing this issue? If so, could you post a [gist](https://gist.github.com/) of a complete npm install on OS X? I suspect there may be native package compilation errors.

**Comment by peterblazejewicz** [comment]
@eanders-MS 
yes, to be strict: this does not stop emulator from working correctly (at least the all usuall features I know seems to work)

The installation tree (under Node 6.*) on OS X is posted in [this gist](https://gist.github.com/peterblazejewicz/ab241927df3ee9699366f7f9b45dcb42)

**Comment by eanders-MS** [comment]
All seems to be ok in the gist. Thank you for taking the time to create it.

I heard someone mention this might happen if you've updated XCode recently, but have not opened it and accepted the new terms. Just a shot in the dark there. Glad to hear it isn't blocking you from running a local build of the app.

**Comment by eanders-MS** [comment]
Hi @peterblazejewicz, closing this issue now but tracking it internally.
