### ISSUE TITLE
Failed to read file: {DIR}/botframework-emulator/server.json

### ISSUE THREAD

**Issue by peterblazejewicz** [Microsoft/BotFramework-Emulator#22]
I've got this error only on Windows (Win 10) but I'll check at home on OS X.
Is this expected to get this error when running with clean state? I'm running emulator from source code.
The file is not yet created at all (`server.json`) hence that error. There are other files in emulator data directory, like `client.json`.

https://github.com/Microsoft/BotFramework-Emulator/blob/82b84e5975351b321258f502803966afb2b99217/src/utils.ts#L66

Full error:
```bash
> botframework-emulator@3.5.20 start C:\dev\BotFramework-Emulator
> electron .


Failed to read file: C:\Users\{USER}\AppData\Roaming\botframework-emulator/botframework-emulator/server.json 
{ Error: ENOENT: no such file or directory, stat 'C:\ Users\{USER}\AppData\Roaming\botframework-emulator\botframework-emulator\server.js
 on'
    at Error (native)
    at fs.statSync (fs.js:992:18)
    at Object.fs.statSync (ELECTRON_ASAR.js:285:16)
    at Object.exports.loadSettings (C:\dev\BotFramework-Emulator\app\utils.js:55:23)
    at Object.exports.getStore (C:\dev\BotFramework-Emulator\app\server\settings.js:61:39)
    at Object.exports.startup (C:\dev\BotFramework-Emulator\app\server\settings.js:114:13)
    at Function.Emulator.startup (C:\dev\BotFramework-Emulator\app\server\emulator.js:62:18)
    at Object.<anonymous> (C:\dev\BotFramework-Emulator\app\server\main.js:143:25)
    at Module._compile (module.js:556:32)
    at Object.Module._extensions..js (module.js:565:10)
  errno: -4058,
  code: 'ENOENT',
  syscall: 'stat',
  path: 'C:\\Users\\{USER}\\AppData\\Roaming\\botframework-emulator\\botframework-emulator\\server.json' }
restarting Emulator because undefined !== 9002
````

It this expected - as I haven't yet started local bot server?

Thanks!
Windows 10
Node 6.9.* (LTS)

**Comment by eanders-MS** [comment]
This being a young application we wanted to err on the side of verbosity when errors happen, so that users would be able to provide details when they report issues.

This particular instance isn't actually reporting an error state, just a failure to find the file, which is fine.

We'll make the app less spammy over time.
