### ISSUE TITLE
[err-server] spawn EACCES

### ISSUE THREAD

**Issue by awitherow** [Microsoft/BotFramework-Emulator#235]
I have set up the app, installed ngrok to my `usr/local/bin/ngrok`, run chmod +x on that to make sure it is executable...

Open up bot emulator to attempt to get started, get this error on start.

```bash

Log
[17:24:19] Emulator listening on http://[::]:56699 
[17:24:19] [err-server] spawn EACCES "Error: spawn EACCES
 at exports._errnoException (util.js:1022:11)
 at ChildProcess.spawn (internal/child_process.js:313:11)
 at exports.spawn (child_process.js:399:9)
 at runNgrok (/private/var/folders/7l/__ztpkv95tn9qmm7gqz3j5wh0000gn/T/AppTranslocation/6D66A142-2FA3-455C-8DDC-59822C59E134/d/botframework-emulator.app/Contents/Resources/app/app/server/ngrok.js:110:13)
 at run (/private/var/folders/7l/__ztpkv95tn9qmm7gqz3j5wh0000gn/T/AppTranslocation/6D66A142-2FA3-455C-8DDC-59822C59E134/d/botframework-emulator.app/Contents/Resources/app/app/server/ngrok.js:68:13)
 at /private/var/folders/7l/__ztpkv95tn9qmm7gqz3j5wh0000gn/T/AppTranslocation/6D66A142-2FA3-455C-8DDC-59822C59E134/d/botframework-emulator.app/Contents/Resources/app/app/server/ngrok.js:78:13
 at lock (/private/var/folders/7l/__ztpkv95tn9qmm7gqz3j5wh0000gn/T/AppTranslocation/6D66A142-2FA3-455C-8DDC-59822C59E134/d/botframework-emulator.app/Contents/Resources/app/node_modules/lock/index.js:72:7)
 at Object.connect (/private/var/folders/7l/__ztpkv95tn9qmm7gqz3j5wh0000gn/T/AppTranslocation/6D66A142-2FA3-455C-8DDC-59822C59E134/d/botframework-emulator.app/Contents/Resources/app/app/server/ngrok.js:62:5)
 at startNgrok (/private/var/folders/7l/__ztpkv95tn9qmm7gqz3j5wh0000gn/T/AppTranslocation/6D66A142-2FA3-455C-8DDC-59822C59E134/d/botframework-emulator.app/Contents/Resources/app/app/server/botFrameworkService.js:101:23)
 at ngrok.kill (/private/var/folders/7l/__ztpkv95tn9qmm7gqz3j5wh0000gn/T/AppTranslocation/6D66A142-2FA3-455C-8DDC-59822C59E134/d/botframework-emulator.app/Contents/Resources/app/app/server/botFrameworkService.js:147:17)" 
[17:24:20] Checking for new version... 
[17:24:20] Application is up to date. 
```

macOS Sierra 10.12.5

**Comment by awitherow** [comment]
Checking here: https://github.com/Microsoft/BotFramework-Emulator/wiki/Tunneling-(ngrok) not very useful screenshots.

**Comment by awitherow** [comment]
Here seems to be the location of the error emission: https://github.com/Microsoft/BotFramework-Emulator/blob/fb72a3d7a29f085ba886c01af6fe692603e09edd/src/server/main.ts#L46

I have looked at other issues, https://github.com/shanalikhan/code-settings-sync/issues/327#issuecomment-303977528

and have attempted to run `chmod +x /usr/local/bin/ngrok` with no effect.

Attempting restart.

**Comment by eanders-MS** [comment]
Perhaps the account you used to install ngrok was an admin, and the emulator is running as a normal user? Just a shot in the dark here, I'm not well-versed on OSX file permissions.

**Comment by awitherow** [comment]
@eanders-MS good idea. I will look into permissions on fixing the permissions for the emulator application its self.

**Comment by awitherow** [comment]
I figured doing a chown, recursively, to root would work... did not.

**Comment by eanders-MS** [comment]
Can you verify that you're able to run ngrok from the command line?

**Comment by eanders-MS** [comment]
Closing due to inactivity. Reply here if you still need assistance and I will reopen.

**Comment by awitherow** [comment]
Sorry @eanders-MS I honestly just gave up trying to get this working as I kept running into trouble and will not be pursuing work with the bot framework anytime soon. I wish you guys luck and I hope that if anyone runs into this issue as I have that they can figure it out!
