### ISSUE TITLE
[04:53:15] [err-server] listen EACCES 0.0.0.0:3979 "Error: listen EACCES 0.0.0.0:3979

### ISSUE THREAD

**Issue by endricott** [Microsoft/BotFramework-Emulator#24]
[04:53:15] [err-server] listen EACCES 0.0.0.0:3979 "Error: listen EACCES 0.0.0.0:3979\n at Object.exports._errnoException (util.js:1026:11)\n at exports._exceptionWithHostPort (util.js:1049:20)\n at Server._listen2 (net.js:1240:19)\n at listen (net.js:1289:10)\n at Server.listen (net.js:1385:5)\n at Server.listen (C:\\Users\\illdo\\AppData\\Local\\botframework\\app-3.5.20\\resources\\app\\node_modules\\restify\\lib\\server.js:398:32)\n at BotFrameworkService.RestServer.restart (C:\\Users\\illdo\\AppData\\Local\\botframework\\app-3.5.20\\resources\\app\\app\\server\\restServer.js:59:28)\n at BotFrameworkService.configure (C:\\Users\\illdo\\AppData\\Local\\botframework\\app-3.5.20\\resources\\app\\app\\server\\botFrameworkService.js:84:18)\n at new BotFrameworkService (C:\\Users\\illdo\\AppData\\Local\\botframework\\app-3.5.20\\resources\\app\\app\\server\\botFrameworkService.js:64:14)\n at new Emulator (C:\\Users\\illdo\\AppData\\Local\\botframework\\app-3.5.20\\resources\\app\\app\\server\\emulator.js:45:26)" 
[04:53:16] Checking for new version... 
[04:53:16] Application is up to date.

**Comment by endricott** [comment]
does any one knows how can i fix it? trying to debug my bot locally, but emulator starting with error already

**Comment by eanders-MS** [comment]
Hi @endricott It looks like you might have had another process already listening on port 3979. Is it possible you had a bot running locally bound to that port when you got this error?

Another observation: Port 3979 is not the default port of the emulator. The emulator defaults to 9002. Is this something you changed in the emulator's App Settings?

**Comment by eanders-MS** [comment]
Hi @endricott If you set your emulator back to port 9002 and then try to chat with your bot running on localhost:3929, do you have better luck?

**Comment by eanders-MS** [comment]
Closing this issue due to inactivity. If you're still having problems, please open a new one.
