### ISSUE TITLE
Startup: Emulator switches to blank window after startup

### ISSUE THREAD

**Issue by KosiehBarter** [Microsoft/BotFramework-Emulator#2472]
## Version
4.15.1-linux

## Describe the bug
White blank window with no input elements (buttons, input fields) after random set of time (mostly 15-30 seconds) after program startup.

## To Reproduce
1. Have Arch Linux distro installed.
2. Set the `BotFramework-Emulator-4.15.1-linux-x86_64.AppImage` binary as executable either graphically or `chmod +x`.
3. Execute the `BotFramework-Emulator-4.15.1-linux-x86_64.AppImage` binary either via terminal or double-click
4. Wait for the Emulator to load completelly
5. Wait up to 30 seconds for the white blank screen to occur

## Expected behavior
Bot Framework Emulator is expected to have input fields fully loaded

## Screenshots
![Image](https://github.com/user-attachments/assets/c422384c-d1bb-41db-9f05-461bf23a457c)

## Additional context
`uname -ar`
Linux b550msl 6.11.4-arch2-1 #1 SMP PREEMPT_DYNAMIC Sun, 20 Oct 2024 18:20:12 +0000 x86_64 GNU/Linux
Desktop Environment: MATE
Distribution: Arch Linux

## I am aware of:
- https://stackoverflow.com/search?q=%5Bbotframework%5D+blank&s=346a1f98-071e-4457-8340-1997ae577376

## Start-up log when running via command line:
./BotFramework-Emulator-4.15.1-linux-x86_64.AppImage 
(node:3066) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `@bfemulatormain --trace-deprecation ...` to show where the warning was created)
[3066:1024/103712.261586:ERROR:object_proxy.cc(590)] Failed to call method: org.freedesktop.portal.Settings.Read: object_path= /org/freedesktop/portal/desktop: org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
libva error: vaGetDriverNames() failed with unknown libva error
Error reading file /home/USER/.config/@bfemulator/main/botframework-emulator/bots.json: Error: ENOENT: no such file or directory, stat '/home/USER/.config/@bfemulator/main/botframework-emulator/bots.json'
Removing extension JSON
Adding extension JSON
Removing extension LUIS
Adding extension LUIS
Removing extension QNAMaker
Adding extension QNAMaker
Server listens on port 41725
Web Socket host server listening on 38651...

**Comment by rido-min** [comment]
Hi @KosiehBarter 

Thanks for reporting this issue. Can you confirm this issue does not repro in the previous version?

From the start-up log, this seems an electron issue in ArchLinux, related to desktop notifications, not sure if this article might help https://wiki.archlinux.org/title/Desktop_notifications#Standalone

**Comment by KosiehBarter** [comment]
I was using previous version of the Emulator and it was working.
I have also realized, that I have not added my version of DE I use. Will update the message.

EDIT:
Older version had troubles with:
`4959:1024/222646.872184:FATAL:gpu_data_manager_impl_private.cc(445)] GPU process isn't usable. Goodbye`

Adding a `--no-sandbox` in commandline has started the older version, newer version has the same bug as without the argument.

**Comment by ydalton** [comment]
I can reproduce this issue with the latest version of the Emulator, version 4.15.1. Within 8 seconds I get the blank screen. This seems to be a regression, I used version 4.8.0 and I did not have any issue. I am running Gentoo Linux with KDE Plasma desktop. Here are the logs, first from version 4.15.1:
```
(node:11444) [DEP0111] DeprecationWarning: Access to process.binding('http_parser') is deprecated.
(Use `@bfemulatormain --trace-deprecation ...` to show where the warning was created)
Error reading file /home/xxxx/.config/@bfemulator/main/botframework-emulator/bots.json: Error: ENOENT: no such file or directory, stat '/home/xxxx/.config/@bfemulator/main/botframework-emulator/bots.json'
Removing extension JSON
Adding extension JSON
Removing extension LUIS
Adding extension LUIS
Removing extension QNAMaker
Adding extension QNAMaker
Server listens on port 45435
[11477:1118/150844.983193:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 1 times!
Web Socket host server listening on 46713...
[11477:1118/150847.220100:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 2 times!
[11477:1118/150854.488326:ERROR:gl_surface_presentation_helper.cc(260)] GetVSyncParametersIfAvailable() failed for 3 times!
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:94495)
    at WebContents.send (node:electron/js2c/browser_init:2:79721)
    at Object.dispatch (/tmp/.mount_BotFraiqi0O8/resources/app.asar/app/server/state/middleware/forwardToRenderer.js:56:59)
    at dispatch (/tmp/.mount_BotFraiqi0O8/resources/app.asar/app/server/state/store.js:101:34)
    at BrowserWindow.<anonymous> (/tmp/.mount_BotFraiqi0O8/resources/app.asar/app/server/main.js:296:31)
    at BrowserWindow.emit (node:events:513:28)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:94495)
    at WebContents.send (node:electron/js2c/browser_init:2:79721)
    at Object.dispatch (/tmp/.mount_BotFraiqi0O8/resources/app.asar/app/server/state/middleware/forwardToRenderer.js:56:59)
    at dispatch (/tmp/.mount_BotFraiqi0O8/resources/app.asar/app/server/state/store.js:101:34)
    at BrowserWindow.<anonymous> (/tmp/.mount_BotFraiqi0O8/resources/app.asar/app/server/main.js:296:31)
    at BrowserWindow.emit (node:events:513:28)
Error sending from webFrameMain:  Error: Render frame was disposed before WebFrameMain could be accessed
    at WebFrameMain.send (node:electron/js2c/browser_init:2:94495)
    at WebContents.send (node:electron/js2c/browser_init:2:79721)
    at Object.dispatch (/tmp/.mount_BotFraiqi0O8/resources/app.asar/app/server/state/middleware/forwardToRenderer.js:56:59)
    at dispatch (/tmp/.mount_BotFraiqi0O8/resources/app.asar/app/server/state/store.js:101:34)
    at BrowserWindow.<anonymous> (/tmp/.mount_BotFraiqi0O8/resources/app.asar/app/server/main.js:296:31)
    at BrowserWindow.emit (node:events:513:28)
```
And from version 4.8.0:
```
zenity, kdialog, Xdialog missing. Skipping /tmp/.mount_BotFraCCadHD/AppRun.
Error reading file /home/xxxx/.config/@bfemulator/main/botframework-emulator/bots.json: Error: ENOENT: no such file or directory, stat '/home/xxxx/.config/@bfemulator/main/botframework-emulator/bots.json'
Removing extension JSON
Adding extension JSON
Removing extension LUIS
Adding extension LUIS
Removing extension QNAMaker
Adding extension QNAMaker
Web Socket host server listening on 36307...
```
From these logs, it looks like an Electron error.

**Comment by sepatel** [comment]
Confirmed that I'm getting the same error under Linux Mint. The previous version works fine (4.14.1) but the latest (4.15.1) does not.

Roughly about a 3 to 4 second screentime before it goes blank. Indeed appears to be an electron error.

**Comment by KeithHanson** [comment]
Experiencing this today on version 4.15.1

**Comment by rbnswartz** [comment]
Same issue on 4.15.1 on Ubuntu 24.04

**Comment by rido-min** [comment]
I downloaded the artifacts from this [run](https://github.com/microsoft/BotFramework-Emulator/actions/runs/13149260917)

And the app opens in Ubuntu 24.04.2

![Image](https://github.com/user-attachments/assets/d712342b-fa16-419e-942d-800597d6b6e3)

Can you check if are there any logs with some details? (View->Toggle Developer Tools)

**Comment by patrickjaja** [comment]
workaround:
 - the version before is still working https://github.com/microsoft/BotFramework-Emulator/releases/tag/v4.14.1

**Comment by huberemanuel** [comment]
v4.14.1 works but it doesn´t have single tenant support, any workarounds?
