### ISSUE TITLE
Error installing npm modules while building from source on Arch Linux (and Arch variants)

### ISSUE THREAD

**Issue by trentandraka** [Microsoft/BotFramework-Emulator#307]
I'm running Manjaro Linux x86_64 and trying to build the emulator from source (since there's no package on the AUR for me to install it from), and when I run 'sudo npm install' in the directory after cloning it, I get the following error (see the error with electron, I'm not sure if the warnings are anything to worry about):

```npm WARN deprecated node-uuid@1.4.7: Use uuid module instead
npm WARN deprecated node-uuid@1.4.8: Use uuid module instead
npm WARN deprecated minimatch@0.2.12: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@2.0.10: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated minimatch@0.2.14: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue
npm WARN deprecated graceful-fs@1.2.3: graceful-fs v3.0.0 and before will fail on node releases >= v7.0. Please update to graceful-fs@^4.0.0 as soon as possible. Use 'npm ls graceful-fs' to find it in the tree.
npm WARN deprecated minimatch@0.3.0: Please update to minimatch 3.0.2 or higher to avoid a RegExp DoS issue

> fcopy-pre-bundled@0.3.4 install /home/trentandraka/BotFramework-Emulator/node_modules/fcopy-pre-bundled
> echo ''



> dtrace-provider@0.8.5 install /home/trentandraka/BotFramework-Emulator/node_modules/bunyan/node_modules/dtrace-provider
> node scripts/install.js


> dtrace-provider@0.6.0 install /home/trentandraka/BotFramework-Emulator/node_modules/dtrace-provider
> node scripts/install.js


> electron-chromedriver@1.7.1 install /home/trentandraka/BotFramework-Emulator/node_modules/electron-chromedriver
> node ./download-chromedriver.js

/home/trentandraka/BotFramework-Emulator/node_modules/electron-chromedriver/download-chromedriver.js:16
  if (error != null) throw error
                     ^

Error: EACCES: permission denied, mkdir '/home/trentandraka/BotFramework-Emulator/node_modules/electron-chromedriver/.electron'
npm WARN The package restify is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-win@2.1.1 (node_modules/7zip-bin-win):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-win@2.1.1: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-mac@1.0.1 (node_modules/7zip-bin-mac):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-mac@1.0.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-chromedriver@1.7.1 install: `node ./download-chromedriver.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-chromedriver@1.7.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-10-14T05_05_04_987Z-debug.log
```

Then, when I do `npm run start` after building (it still builds fine), I get this error:
```> botframework-emulator@3.5.32 start /home/trentandraka/BotFramework-Emulator
> electron .

/home/trentandraka/BotFramework-Emulator/node_modules/electron/index.js:9
  throw new Error('Electron failed to install correctly, please delete node_modules/electron and try installing again')
  ^

Error: Electron failed to install correctly, please delete node_modules/electron and try installing again
    at Object.<anonymous> (/home/trentandraka/BotFramework-Emulator/node_modules/electron/index.js:9:9)
    at Module._compile (module.js:624:30)
    at Object.Module._extensions..js (module.js:635:10)
    at Module.load (module.js:545:32)
    at tryModuleLoad (module.js:508:12)
    at Function.Module._load (module.js:500:3)
    at Module.require (module.js:568:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/trentandraka/BotFramework-Emulator/node_modules/electron/cli.js:3:16)
    at Module._compile (module.js:624:30)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! botframework-emulator@3.5.32 start: `electron .`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the botframework-emulator@3.5.32 start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/trentandraka/.npm/_logs/2017-10-14T05_09_48_960Z-debug.log
```

Running `sudo npm install` again just gives me the same error:
```> electron-chromedriver@1.7.1 install /home/trentandraka/BotFramework-Emulator/node_modules/electron-chromedriver
> node ./download-chromedriver.js

/home/trentandraka/BotFramework-Emulator/node_modules/electron-chromedriver/download-chromedriver.js:16
  if (error != null) throw error
                     ^

Error: EACCES: permission denied, mkdir '/home/trentandraka/BotFramework-Emulator/node_modules/electron-chromedriver/.electron'
npm WARN The package restify is included as both a dev and production dependency.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-win@2.1.1 (node_modules/7zip-bin-win):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-win@2.1.1: wanted {"os":"win32","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: 7zip-bin-mac@1.0.1 (node_modules/7zip-bin-mac):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for 7zip-bin-mac@1.0.1: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! electron-chromedriver@1.7.1 install: `node ./download-chromedriver.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the electron-chromedriver@1.7.1 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2017-10-14T05_13_17_251Z-debug.log
```
How can I fix the error with the electron module? Searching for it online yielded no solutions.

**Comment by eanders-MS** [comment]
> Error: EACCES: permission denied, mkdir '/home/trentandraka/BotFramework-Emulator/node_modules/electron-chromedriver/.electron'

This appears to be an OS/permissions issue, not an issue with the emulator codebase. You might have better luck asking in the npm forums.
