### ISSUE TITLE
Not able to get it working with the service 

### ISSUE THREAD

**Issue by bchen007** [Microsoft/BotFramework-Emulator#633]
I cannot seem to get the emulator working at all. Every time I typed something, I am getting an error below:

[15:19:15]POST500directline.postActivity

I extracted an error from the inspector and I don't have a clue where the IP address and port number came from in the error message. 
A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 10.223.98.151:64197

**Comment by JasonSowers** [comment]
Hi @bchen007, what endpoint are you putting into the emulator?  Is this bot node/C#? Can you please walk us through the problem and your setup.  Right now there is not really enough information to diagnose this.

**Comment by JasonSowers** [comment]
Closing as no reponse

**Comment by bchen007** [comment]
Hi Jason,
I was about to respond today. Sorry I was busy working on something else for a while.
I have tried the simulator with my bot using node and C# and getting the same error. Here is the endpoint configured in the emulator:
http://localhost:3978/api/messages

From what I can tell, the bot did receive the message from the emulator. The error is resulted from the bot not being able to send the response back to the emulator. Here is the error message:
A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 10.223.98.151:64197    

CM    On Friday, June 29, 2018, 12:55:11 PM MST, Jason Sowers <notifications@github.com> wrote:  
 
 
Closed #633.

**Comment by bchen007** [comment]
I reinstalled the packages following online instructions here 

I created a test bot using javascripts. When I ran the emulator, I am getting an error in Node. I don't have any configuration in .env. node app.jsrestify listening to http://[::]:3978BotFrameworkAdapter.processActivity(): 500 ERROR - FetchError: request to http://http:57070/v3/conversations/0487ab80-7ee9-11e8-9240-814098376b4a%7Clivechat/activities/68fa6770-7eed-11e8-95b5-9fe30731cdba fail//http:57070/v3/conversations/0487ab80-7ee9-11e8-9240-814098376b4a%7Clivechat/activities/68fa6770-7eed-11e8-95b5-9fe30731cdba failed, reason: getaddrinfo ENOTtp:57070/v3/conversations/0487ab80-7ee9-11e8-9240-814098376b4a%7Clivechat/activities/68fa6770-7eed-11e8-95b5-9fe30731cdba failed,FOUND http http:57070(node:16908) UnhandledPromiseRejectionWarning: FetchError: request to http://htot-js\node_modules\node-fetch\index.js:133:11)tp:57070/v3/conversations/0487ab80-7ee9-11e8-9240-814098376b4a%7Clivechat/activities/68fa6770-7eed-11e8-95b5-9fe30731cdba failed, reason: getaddrinfo ENOTFOUND http http:57070    at ClientRequest.<anonymous> (C:\Users\ccmatloc\source\repos\myJsBots\cma-bot-js\node_modules\node-fetch\index.js:133:11)    at ClientRequest.emit (events.js:182:13)    at ClientRequest.EventEmitter.emit (domain.js:442:20)    at Socket.socketErrorListener (_http_client.js:382:9)    at Socket.emit (events.js:182:13)    at Socket.EventEmitter.emit (domain.js:442:20)    at emitErrorNT (internal/streams/destroy.js:82:8)    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)    at process._tickCallback (internal/process/next_tick.js:63:19)(node:16908) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)(node:16908) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
    On Friday, June 29, 2018, 3:31:11 PM MST, Christine Chen Matlock <bchen007@yahoo.com> wrote:  
 
  
Hi Jason,
I was about to respond today. Sorry I was busy working on something else for a while.
I have tried the simulator with my bot using node and C# and getting the same error. Here is the endpoint configured in the emulator:
http://localhost:3978/api/messages

From what I can tell, the bot did receive the message from the emulator. The error is resulted from the bot not being able to send the response back to the emulator. Here is the error message:
A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 10.223.98.151:64197    

CM    On Friday, June 29, 2018, 12:55:11 PM MST, Jason Sowers <notifications@github.com> wrote:  
 
 
Closed #633.

**Comment by JasonSowers** [comment]
Are you using a sample? if so which? Can you share your code, please?  500 error is a generic error that is hard to diagnose without the code.

**Comment by bchen007** [comment]
I just used the generator to create the bot and I did not change any code nor configuration.
yo botbuilder

I selected Javascript for the bot.  Here is the error message that the bot logs after it receives the request from the emulator and I noticed this strange port in the error message and don't know where that came from "http://http:57070/"

restify listening to http://[::]:3978BotFrameworkAdapter.processActivity(): 500 ERROR - FetchError: request to http://http:57070/v3/conversations/0487ab80-7ee9-11e8-9240-814098376b4a%7Clivechat/activities/68fa6770-7eed-11e8-95b5-9fe30731cdba fail//http:57070/v3/conversations/0487ab80-7ee9-11e8-9240-814098376b4a%7Clivechat/activities/68fa6770-7eed-11e8-95b5-9fe30731cdba failed, reason: getaddrinfo ENOTtp:57070/v3/conversations/0487ab80-7ee9-11e8-9240-814098376b4a%7Clivechat/activities/68fa6770-7eed-11e8-95b5-9fe30731cdba failed,FOUND http http:57070(node:16908) UnhandledPromiseRejectionWarning: FetchError: request to http://htot-js\node_modules\node-fetch\index.js:133:11)tp:57070/v3/conversations/0487ab80-7ee9-11e8-9240-814098376b4a%7Clivechat/activities/68fa6770-7eed-11e8-95b5-9fe30731cdba failed, reason: getaddrinfo ENOTFOUND http http:57070    at ClientRequest.<anonymous> (C:\Users\ccmatloc\source\repos\myJsBots\cma-bot-js\node_modules\node-fetch\index.js:133:11)    at ClientRequest.emit (events.js:182:13)    at ClientRequest.EventEmitter.emit (domain.js:442:20)    at Socket.socketErrorListener (_http_client.js:382:9)    at Socket.emit (events.js:182:13)    at Socket.EventEmitter.emit (domain.js:442:20)    at emitErrorNT (internal/streams/destroy.js:82:8)    at emitErrorAndCloseNT (internal/streams/destroy.js:50:3)    at process._tickCallback (internal/process/next_tick.js:63:19)(node:16908) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 4)(node:16908) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code. 
    On Tuesday, July 3, 2018, 6:18:06 PM EDT, Jason Sowers <notifications@github.com> wrote:  
 
 
Are you using a sample? if so which? Can you share your code, please? 500 error is a generic error that is hard to diagnose without the code.

**Comment by cverdon** [comment]
I have the same issue. I created and slightly modified the default EchoBot SDK v4. When running on localhost everything is fine. Once published to Bot Service, it works fine from the Azure Portal "web chat", but unable to connect to it with the 4.0.15 Preview...

**Comment by JasonSowers** [comment]
So you both are using the emulator with the URL being the https://{BotName}.azurewebsites.net URL and you have the app ID and password in the emulator?  

I want to understand this so I can reproduce accordingly.

**Comment by bchen007** [comment]
I don't have any appid and password configured. Actually one of my colleagues installed the framework and don't seem to have this issue. Before I was thinking this is related to security configuration on the network, but I am not sure why other people don't have this problem.
    On Monday, July 9, 2018, 12:31:31 PM PDT, Jason Sowers <notifications@github.com> wrote:  
 
 
So you both are using the emulator with the URL being the https://{BotName}.azurewebsites.net URL and you have the app ID and password in the emulator?

I want to understand this so I can reproduce accordingly.

**Comment by bchen007** [comment]
I just installed the older version of the emulator (3.5.36) and it is working for me.
    On Monday, July 9, 2018, 2:59:42 PM PDT, Christine Chen Matlock <bchen007@yahoo.com> wrote:  
 
  I don't have any appid and password configured. Actually one of my colleagues installed the framework and don't seem to have this issue. Before I was thinking this is related to security configuration on the network, but I am not sure why other people don't have this problem.
    On Monday, July 9, 2018, 12:31:31 PM PDT, Jason Sowers <notifications@github.com> wrote:  
 
 
So you both are using the emulator with the URL being the https://{BotName}.azurewebsites.net URL and you have the app ID and password in the emulator?

I want to understand this so I can reproduce accordingly.

**Comment by JasonSowers** [comment]
@cverdon when you say slightly modified echobot, do you mean the echobot from the VS template or the echobot sample from the botbuilder-dotnet repository? Please try this sample on the v3 emulator and see if it works there for you.  I think I have an idea of what is going on here and want to investigate it.

**Comment by JasonSowers** [comment]
Closing as no response, Please open a new issue if you require further assistance.

**Comment by lumayara** [comment]
I had the same issue and fixed by uninstalling the alpha 4 version and installing the version 3.
