### ISSUE TITLE
Version 4.0.15 doesn't support Bot Application security locally

### ISSUE THREAD

**Issue by 14geronimo** [Microsoft/BotFramework-Emulator#670]
Could you please confirm the behaviour explained in Test 2 below is indeed a bug in 4.0.15-alpha?
Please also confirm the difference of behaviour noted in Test 3 is an intended change of functionality in v4?
Many thanks

Environment:
- Microsoft Visual Studio Professional 2017 | Version 15.7.4 | VisualStudio.15.Release/15.7.4+27703.2035
- Microsoft .NET Framework | Version 4.7.02046
- Microsoft Windows 10 Enterprise | Version 10.0.15063 Build 15063

Testing against:
- Bot Framework Emulator (V4 PREVIEW) | Version 4.0.15-alpha
- Bot Framework Emulator | Version 3.5.36

Test 1: Bot application running with blank Id/Password values under IIS Express in Visual Studio on localhost. Emulator connections configured with blank Id/Password
Observations: Both tests are successful, the bot responds as expected in each emulator
![Test 1](https://user-images.githubusercontent.com/48331/42232652-07dbb5a8-7ee7-11e8-94c0-0cdb6f7bebd3.png)

Test 2:  Bot application running with a Id/Password values "228fc2ba-282f-44b0-917b-51a2a5730373"/"wn*******************;}" running under IIS Express in Visual Studio on localhost as above. Emulator connections configured with the same Id/Password
Observations: Only 3.5.36 test is successful, with 4.0.15, the response is "POST 401 directline.postActivity" and the breakpoint in Visual Studio is never reached
![Test 2](https://user-images.githubusercontent.com/48331/42232757-4f42f74e-7ee7-11e8-91a2-affada27b08c.png)

Test 3: Bot applicarion running with blank Id/Password values. Emulator connections configured with non-blank Id/Password values as above
Observations: The behaviour is different between the two versions:
- v3.5.6 rejects the connection with HTTP 500, the emulator insists that it should be configured with blank Id/Password since the application is running without security
- v4.0.15 ignores the Id/Password values, and carries on as if the connection was configured with blank Id/Password
![Test 3](https://user-images.githubusercontent.com/48331/42233007-1aaa96ee-7ee8-11e8-98e8-50540b0794f8.png)

**Comment by justinwilaby** [comment]
I am seeing a problem but it does not appear to be with the Emulator. I've tested all paths mentioned above and cannot repro any of them when the *locally running bot is restarted* between each test. If an appId and password are provided, the emulator correctly retrieves an `auth_token` from the [auth endpoint](https://github.com/Microsoft/BotFramework-Emulator/blob/v4.1/packages/emulator/core/src/authEndpoints.ts#L35) before [posting the activity to the bot](https://github.com/Microsoft/BotFramework-Emulator/blob/v4.1/packages/emulator/core/src/facility/conversation.ts#L112).
If the appId is omitted, no `Authorization` header is [sent to the endpoint](https://github.com/Microsoft/BotFramework-Emulator/blob/v4.1/packages/emulator/core/src/facility/botEndpoint.ts#L99).

When I do not kill the bot and restart it between test cases and begin the first test case with an appId and password, the `BotFrameworkAdapter` produces a 401 after removing the appId and password from my bot file and starting a new conversation. The problem is that this is an *uncaught* exception which surfaces as a `500` **not** a `401` as it should:
>BotFrameworkAdapter.processActivity(): 401 ERROR - Error: Unauthorized Access. Request is not authorized
(node:79963) UnhandledPromiseRejectionWarning: Error: Unauthorized Access. Request is not authorized
    at Object.<anonymous> (/Users/microsoft/Documents/dev/BotBuilder-Samples/samples/javascript_nodejs/12.nlp-with-luis/node_modules/botframework-connector/lib/auth/jwtTokenValidation.js:34:23)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/microsoft/Documents/dev/BotBuilder-Samples/samples/javascript_nodejs/12.nlp-with-luis/node_modules/botframework-connector/lib/auth/jwtTokenValidation.js:4:58)
    at internalTickCallback (internal/process/next_tick.js:77:7)
    at _tickCallback (internal/process/next_tick.js:47:5)
    at processImmediate (timers.js:605:7)
    at process.topLevelDomainCallback (domain.js:120:23)
(node:79963) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:79963) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
BotFrameworkAdapter.processActivity(): 401 ERROR - Error: Unauthorized Access. Request is not authorized
(node:79963) UnhandledPromiseRejectionWarning: Error: Unauthorized Access. Request is not authorized
    at Object.<anonymous> (/Users/microsoft/Documents/dev/BotBuilder-Samples/samples/javascript_nodejs/12.nlp-with-luis/node_modules/botframework-connector/lib/auth/jwtTokenValidation.js:34:23)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/microsoft/Documents/dev/BotBuilder-Samples/samples/javascript_nodejs/12.nlp-with-luis/node_modules/botframework-connector/lib/auth/jwtTokenValidation.js:4:58)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
(node:79963) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
BotFrameworkAdapter.processActivity(): 401 ERROR - Error: Unauthorized Access. Request is not authorized
(node:79963) UnhandledPromiseRejectionWarning: Error: Unauthorized Access. Request is not authorized
    at Object.<anonymous> (/Users/microsoft/Documents/dev/BotBuilder-Samples/samples/javascript_nodejs/12.nlp-with-luis/node_modules/botframework-connector/lib/auth/jwtTokenValidation.js:34:23)
    at Generator.next (<anonymous>)
    at fulfilled (/Users/microsoft/Documents/dev/BotBuilder-Samples/samples/javascript_nodejs/12.nlp-with-luis/node_modules/botframework-connector/lib/auth/jwtTokenValidation.js:4:58)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)
(node:79963) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 3)

@14geronimo - Can you run through your test cases again with the latest emulator but restart the local bot with each one and see if your results corroborate with mine?

**Comment by justinwilaby** [comment]
@Stevenic @stevengum - Are you able to add some context on this?

**Comment by vishwacsena** [comment]
@14geronimo can you please try to repro with the 4.1.0 version of emulator available [here](https://github.com/Microsoft/BotFramework-Emulator/releases/tag/v4.1.0)
