### ISSUE TITLE
GET to 'https://state.botframework.com/v3/botstate/webchat/conversations/0560d6047ba04687bd762e7e86a1b6ca/users/A8r4akHZE1Z' failed: [405] Method Not Allowed

### ISSUE THREAD

**Issue by brillioai** [Microsoft/BotFramework-Emulator#759]
Hi Everyone, 

We developed a Bot using Bot Builder recently and deployed on to Azure. The Bot is running fine locally and is deployed on to Azure. However, when try to test the Bot from Web Channel or Azure Test Tab, the output console is displaying the below error:

Error: GET to 'https://state.botframework.com/v3/botstate/webchat/conversations/0560d6047ba04687bd762e7e86a1b6ca/users/A8r4akHZE1Z' failed: [405] Method Not Allowed
    at Request._callback (D:\home\site\wwwroot\node_modules\botbuilder\lib\bots\ChatConnector.js:647:46)
    at Request.self.callback (D:\home\site\wwwroot\node_modules\request\request.js:185:22)
    at emitTwo (events.js:106:13)
    at Request.emit (events.js:191:7)
    at Request.<anonymous> (D:\home\site\wwwroot\node_modules\request\request.js:1157:10)
    at emitOne (events.js:96:13)
    at Request.emit (events.js:188:7)
    at IncomingMessage.<anonymous> (D:\home\site\wwwroot\node_modules\request\request.js:1079:12)
    at IncomingMessage.g (events.js:291:16)
    at emitNone (events.js:91:20)

Kindly help in solving this error.

**Comment by EricDahlvang** [comment]
Please implement a custom state client for the bot.  The default state service has been deprecated: https://blog.botframework.com/2017/12/19/bot-state-service-will-soon-retired-march-31st-2018/

Or, use the in memory state store like:

```js
var inMemoryStorage = new builder.MemoryBotStorage();
var connector = new builder.ConsoleConnector().listen();
var bot = new builder.UniversalBot(connector, function (session) {
    session.send("Say 'help' or something else...");
}).set('storage', inMemoryStorage);
```
