### ISSUE TITLE
Investigate: missing peer dependencies

### ISSUE THREAD

**Issue by compulim** [Microsoft/BotFramework-Emulator#778]
On NPM 6.4.0, repro when:

```
git clone …
npm install
npm run bootstrap
lerna add botframework-webchat@0.14.2 --scope=@bfemulator/client --hoist
```

> I think it is unrelated to `botframework-webchat`, if you do `lerna add` on any packages, it should still repro.

Got errors on `lerna add` because some packages in emulator is missing peer dependencies:

> `@fuselab/ui-fabric@1.1.2` is missing peer dependencies of `@uifabric/icons`, `@uifabric/merge-styles`, `@uifabric/styling`, `@uifabric/utilities`, `react-router-dom`, etc.

```
lerna info version 2.11.0
lerna info versioning independent
lerna info scope @bfemulator/client
lerna info Add dependencies in 1 packages
lerna info Changes require bootstrap in 1 packages
lerna info version 2.11.0
lerna info versioning independent
lerna info scope [ '@bfemulator/client' ]
lerna info Bootstrapping 1 packages
lerna info lifecycle preinstall
lerna info Installing external dependencies
lerna info hoist Installing hoisted dependencies into root
lerna info hoist Pruning hoisted dependencies
lerna info hoist Finished pruning hoisted dependencies
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: npm install
lerna ERR! npm WARN @fuselab/ui-fabric@1.1.2 requires a peer of @uifabric/icons@~5.6.0 but none is installed. You must install peer dependencies yourself.
lerna ERR! npm WARN @fuselab/ui-fabric@1.1.2 requires a peer of @uifabric/merge-styles@~5.13.0 but none is installed. You must install peer dependencies yourself.
lerna ERR! npm WARN @fuselab/ui-fabric@1.1.2 requires a peer of @uifabric/styling@~5.20.0 but none is installed. You must install peer dependencies yourself.
lerna ERR! npm WARN @fuselab/ui-fabric@1.1.2 requires a peer of @uifabric/utilities@~5.19.0 but none is installed. You must install peer dependencies yourself.
lerna ERR! npm WARN @fuselab/ui-fabric@1.1.2 requires a peer of react-router-dom@~4.2.2 but none is installed. You must install peer dependencies yourself.
lerna ERR! npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
lerna ERR! npm WARN babel-loader@7.1.5 requires a peer of babel-core@6 but none is installed. You must install peer dependencies yourself.
lerna ERR! npm WARN react-app-rewired@1.5.2 requires a peer of react-scripts@^1.0.14 but none is installed. You must install peer dependencies yourself.
lerna ERR! npm WARN BotFramework-Emulator No repository field.
lerna ERR! npm WARN BotFramework-Emulator No license field.
lerna ERR! npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
lerna ERR! npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
lerna ERR!
lerna ERR! The batch file cannot be found.
lerna ERR! added 1 package from 2 contributors, removed 943 packages, updated 1 package and audited 45110 packages in 62.67s
lerna ERR! found 1 moderate severity vulnerability
lerna ERR!   run `npm audit fix` to fix them, or `npm audit` for details
lerna ERR!
lerna ERR!     at Promise.all.then.arr (C:\Users\JohnDoe\AppData\Roaming\npm\node_modules\lerna\node_modules\execa\index.js:236:11)
lerna ERR!     at <anonymous>
lerna ERR! execute callback with error
lerna ERR! Error: Command failed: npm install
lerna ERR! npm WARN @fuselab/ui-fabric@1.1.2 requires a peer of @uifabric/icons@~5.6.0 but none is installed. You must install peer dependencies yourself.
lerna ERR! npm WARN @fuselab/ui-fabric@1.1.2 requires a peer of @uifabric/merge-styles@~5.13.0 but none is installed. You must install peer dependencies yourself.
lerna ERR! npm WARN @fuselab/ui-fabric@1.1.2 requires a peer of @uifabric/styling@~5.20.0 but none is installed. You must install peer dependencies yourself.
lerna ERR! npm WARN @fuselab/ui-fabric@1.1.2 requires a peer of @uifabric/utilities@~5.19.0 but none is installed. You must install peer dependencies yourself.
lerna ERR! npm WARN @fuselab/ui-fabric@1.1.2 requires a peer of react-router-dom@~4.2.2 but none is installed. You must install peer dependencies yourself.
lerna ERR! npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
lerna ERR! npm WARN babel-loader@7.1.5 requires a peer of babel-core@6 but none is installed. You must install peer dependencies yourself.
lerna ERR! npm WARN react-app-rewired@1.5.2 requires a peer of react-scripts@^1.0.14 but none is installed. You must install peer dependencies yourself.
lerna ERR! npm WARN BotFramework-Emulator No repository field.
lerna ERR! npm WARN BotFramework-Emulator No license field.
lerna ERR! npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
lerna ERR! npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
lerna ERR!
lerna ERR! The batch file cannot be found.
lerna ERR! added 1 package from 2 contributors, removed 943 packages, updated 1 package and audited 45110 packages in 62.67s
lerna ERR! found 1 moderate severity vulnerability
lerna ERR!   run `npm audit fix` to fix them, or `npm audit` for details
lerna ERR!
lerna ERR!     at Promise.all.then.arr (C:\Users\JohnDoe\AppData\Roaming\npm\node_modules\lerna\node_modules\execa\index.js:236:11)
lerna ERR!     at <anonymous>
{ Error: Command failed: npm install
npm WARN @fuselab/ui-fabric@1.1.2 requires a peer of @uifabric/icons@~5.6.0 but none is installed. You must install peer dependencies yourself.
npm WARN @fuselab/ui-fabric@1.1.2 requires a peer of @uifabric/merge-styles@~5.13.0 but none is installed. You must install peer dependencies yourself.
npm WARN @fuselab/ui-fabric@1.1.2 requires a peer of @uifabric/styling@~5.20.0 but none is installed. You must install peer dependencies yourself.
npm WARN @fuselab/ui-fabric@1.1.2 requires a peer of @uifabric/utilities@~5.19.0 but none is installed. You must install peer dependencies yourself.
npm WARN @fuselab/ui-fabric@1.1.2 requires a peer of react-router-dom@~4.2.2 but none is installed. You must install peer dependencies yourself.
npm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN babel-loader@7.1.5 requires a peer of babel-core@6 but none is installed. You must install peer dependencies yourself.
npm WARN react-app-rewired@1.5.2 requires a peer of react-scripts@^1.0.14 but none is installed. You must install peer dependencies yourself.
npm WARN BotFramework-Emulator No repository field.
npm WARN BotFramework-Emulator No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})

The batch file cannot be found.
added 1 package from 2 contributors, removed 943 packages, updated 1 package and audited 45110 packages in 62.67s
found 1 moderate severity vulnerability
  run `npm audit fix` to fix them, or `npm audit` for details

    at Promise.all.then.arr (C:\Users\JohnDoe\AppData\Roaming\npm\node_modules\lerna\node_modules\execa\index.js:236:11)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
  code: 1,
  killed: false,
  stdout: 'added 1 package from 2 contributors, removed 943 packages, updated 1 package and audited 45110 packages in 62.67s\nfound 1 moderate severity vulnerability\n  run `npm audit fix` to fix them, or `npm audit` for details\n',
  stderr: 'npm WARN @fuselab/ui-fabric@1.1.2 requires a peer of @uifabric/icons@~5.6.0 but none is installed. You must install peer dependencies yourself.\nnpm WARN @fuselab/ui-fabric@1.1.2 requires a peer of @uifabric/merge-styles@~5.13.0 but none is installed. You must install peer dependencies yourself.\nnpm WARN @fuselab/ui-fabric@1.1.2 requires a peer of @uifabric/styling@~5.20.0 but none is installed. You must install peer dependencies yourself.\nnpm WARN @fuselab/ui-fabric@1.1.2 requires a peer of @uifabric/utilities@~5.19.0 but none is installed. You must install peer dependencies yourself.\nnpm WARN @fuselab/ui-fabric@1.1.2 requires a peer of react-router-dom@~4.2.2 but none is installed. You must install peer dependencies yourself.\nnpm WARN ajv-keywords@3.2.0 requires a peer of ajv@^6.0.0 but none is installed. You must install peer dependencies yourself.\nnpm WARN babel-loader@7.1.5 requires a peer of babel-core@6 but none is installed. You must install peer dependencies yourself.\nnpm WARN react-app-rewired@1.5.2 requires a peer of react-scripts@^1.0.14 but none is installed. You must install peer dependencies yourself.\nnpm WARN BotFramework-Emulator No repository field.\nnpm WARN BotFramework-Emulator No license field.\nnpm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\\fsevents):\nnpm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})\n\nThe batch file cannot be found.\r\n',
  failed: true,
  signal: null,
  cmd: 'npm install',
  timedOut: false,
  exitCode: 1 }
```

**Comment by sgellock** [comment]
won't fix.
